# Generated by Django 6.1.1 on 2026-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_outstanding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
